### PR TITLE
Fixes for compilation on Ubuntu 14.04

### PR DESCRIPTION
**Pull request by mkoval**
I had to make two changes to libbarrett to get libbarrett to compile on Ubuntu 14.04:
1. Added a dependency to `CMakeLists.txt` fix a linking error (c123e96)
2. Fixed a compilation error on new versions of GCC (c3adc84)

### CODE REVIEW

**Comment by mkoval** [comment]
I was able to build libbarrett with these changes in a non-RT configuration in the following configurations:
- Ubuntu 12.04 on amd64, GCC 4.6.3, Boost 1.46
- Ubuntu 14.04 on amd64, GCC 4.8.2, Boost 1.54

What are the "supported" configurations that we need to test?

**Comment by bzenowich** [comment]
I can confirm that stock 12.04 and stock 14.04 compile fine with non-RT and RT. It seems boost_system is required for non-RT, but not for RT. I can not pinpoint what exactly depends on boost_system, but perhaps it is a hidden dependency of date_time? In any case, I'm happy with adding "system" to the CMakeLists.txt.
